name: Install
description: Install dependencies

inputs:
  node-version:
    description: Node version
    default: "18"

  python-version:
    description: Python version
    default: "3.8"

runs:
  using: composite
  steps:
    - name: Checkout the source code
      uses: actions/checkout@v3

    - name: Fetch yarn's cache directory path
      id: yarn-cache-dir-path
      shell: bash
      run: echo "YARN_CACHE_DIR=$(yarn cache dir)" >> $GITHUB_ENV

    - name: Set up yarn package caching
      uses: actions/cache@v3
      id: yarn-cache
      with:
        path: ${{ env.YARN_CACHE_DIR }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Set up pip package caching
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-

    - name: Set the node version
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Set the python version
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install node dependencies
      shell: bash
      run: |
        yarn install --frozen-lockfile
        yarn global add nps ts-node

    - name: Install python dependencies
      shell: bash
      run: pip install cppclean emoji scons psutil trufflehog3

    - name: Install apt dependencies
      shell: bash
      run: sudo apt install -y cppcheck doxygen=1.9.1-2ubuntu2
