name: Install
description: Install dependencies

inputs:
  node-version:
    description: Node version
    default: "18"

  python-version:
    description: Python version
    default: "3.10"

runs:
  using: composite
  steps:
    - name: Checkout the source code
      uses: actions/checkout@v4

    - name: Enable corepack
      shell: bash
      run: corepack enable

    - name: Set the node version
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: yarn

    - name: Set the python version
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: pip

    - name: Install yarn dependencies
      shell: bash
      run: yarn install --immutable

    - name: Install pip dependencies
      shell: bash
      run: pip install .[all]

    - name: Install apt dependencies
      shell: bash
      run: sudo apt-get install -y doxygen

    - name: Install conan dependencies
      shell: bash
      run: |
        conan profile detect
        conan install . --build=missing
