name: Review

on: [push, pull_request]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/actions/install

      - name: Run linters
        run: npm run lint
        env:
          CPPPATH: /usr/include

      - name: Run tests
        run: |
          scons test
          ./dist/tests
        env:
          CPPPATH: /usr/include
          LIBPATH: /usr/lib
